/**
 * 
 */
package com.practice.coding;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
/**
 * @author Ganesh Shinde
 *
 */
public class DinnerPartyTest {
	DinnerParty dinnerParty;

	@Before
	public void init() {
		dinnerParty = new DinnerParty();
	}
	
	/**
	 * Test method for {@link com.practice.coding.DinnerParty#getPossibleSeatingArrangementAtDinnerParty(java.util.List, int)}.
	 */
	@Test
	public void testGetPossibleSeatingArrangementAtDinnerParty() {
		List<String> friends = new ArrayList<String>();
		friends.add("Fred");
		friends.add("Paresh");
		friends.add("Tom");
		friends.add("Greenie");
		friends.add("April");
		friends.add("Dick");
		friends.add("Harry");
		friends.add("Lucifer");
		List<List<String>> groups = dinnerParty.getPossibleSeatingArrangementAtDinnerParty(friends, 4);
		groups.removeAll(prepareOutput());
		assertEquals(0, groups.size());
	}
	
	@Test
	public void testGetPossibleSeatingArrangementAtDinnerPartySecond() {
		List<String> friends = new ArrayList<String>();
		friends.add("1");
		friends.add("2");
		friends.add("3");
		friends.add("4");
		List<List<String>> groups = dinnerParty.getPossibleSeatingArrangementAtDinnerParty(friends, 3);
		groups.removeAll(prepareSecondOutput());
		assertEquals(0, groups.size());
		
	}
	
	public List<List<String>> prepareOutput() {
		List<String> group = new ArrayList<String>();
		List<List<String>> groups = new ArrayList<List<String>>();
		group.add("April");
		group.add("Dick");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Greenie");
		group.add("Dick");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Greenie");
		group.add("April");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Greenie");
		group.add("April");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Greenie");
		group.add("April");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("Dick");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("April");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("April");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("April");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("Greenie");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("Greenie");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("Greenie");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("Greenie");
		group.add("April");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("Greenie");
		group.add("April");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Tom");
		group.add("Greenie");
		group.add("April");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Dick");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("April");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("April");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("April");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Greenie");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Greenie");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Greenie");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Greenie");
		group.add("April");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Greenie");
		group.add("April");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Greenie");
		group.add("April");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("April");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("April");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("April");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("Greenie");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("Greenie");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("Greenie");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Paresh");
		group.add("Tom");
		group.add("Greenie");
		group.add("April");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Dick");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("April");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("April");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("April");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Greenie");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Greenie");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Greenie");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Greenie");
		group.add("April");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Greenie");
		group.add("April");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Greenie");
		group.add("April");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("April");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("April");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("April");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("Greenie");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("Greenie");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("Greenie");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Tom");
		group.add("Greenie");
		group.add("April");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Harry");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Dick");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Dick");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("April");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("April");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("April");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Greenie");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Greenie");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Greenie");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Greenie");
		group.add("April");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Tom");
		group.add("Lucifer");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Tom");
		group.add("Harry");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Tom");
		group.add("Dick");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Tom");
		group.add("April");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("Fred");
		group.add("Paresh");
		group.add("Tom");
		group.add("Greenie");
		groups.add(group);
		return groups;
	}
	
	public List<List<String>> prepareSecondOutput() {
		List<String> group = new ArrayList<String>();
		List<List<String>> groups = new ArrayList<List<String>>();
		group.add("2");
		group.add("3");
		group.add("4");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("1");
		group.add("3");
		group.add("4");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("1");
		group.add("2");
		group.add("4");
		groups.add(group);
		group = new ArrayList<String>();
		group.add("1");
		group.add("2");
		group.add("3");
		groups.add(group);
		group = new ArrayList<String>();
		return groups;
	}

}
